#!/usr/bin/env python3
"""Generate the Publications page from the canonical record.

    python3 generators/generate_publications_page.py

WHY (260905). `auto-publications.md` was named "auto" but nothing generated it.
It was frozen output from the theme's old `markdown_generator/publications.json`
(119 entries) and had drifted 26 records behind `data/publications.yaml` --
missing both books, four of the seven current technical reports, and several
conference, journal and workshop papers. The site's most enumerative page was
the one page still hand-maintained, which is precisely the arrangement the
project's own rule forbids: never hand-maintain an enumerative record in page
prose.

Section order and entry shape follow the page it replaces, so this is a change
of SOURCE, not of appearance. The `us-patents` anchor is preserved because the
sidebar's "8 U.S. patents" links to it.
"""

from __future__ import annotations

import pathlib
import sys

import urllib.parse

import _paths
import yaml

# (heading, anchor, id-prefixes) in the order the page presents them.
SECTIONS = [
    ("Peer-reviewed conference papers, full and short", None, ("C",)),
    ("Peer-reviewed journal and magazine papers", None, ("J", "M")),
    ("Peer-reviewed workshop papers", None, ("W",)),
    ("Books and book chapters", None, ("B",)),
    ("Technical reports", None, ("R",)),
    ("US patents", "us-patents", ("Pa",)),
    ("Posters", None, ("Ps",)),
]


def entry(p: dict) -> list[str]:
    """One numbered item: title, authors, venue, link -- the page's own shape."""
    out = [f"1. *{' '.join(p['title'].split())}*.  "]
    if p.get("authors"):
        # The page bolds Davis; the record stores a plain author string.
        au = " ".join(str(p["authors"]).split()).replace("J.C. Davis", "**Davis**")
        out.append(f" {au}.  ")
    venue = p.get("venue") or ""
    year = p.get("year")
    tail = " ".join(x for x in [" ".join(str(venue).split()), str(year) if year else ""] if x)
    if tail:
        out.append(f" {tail}.  ")
    url = p.get("paper_url") or (p.get("links") or {}).get("record")
    if url:
        out.append(f' <a href="{url}"><i class="fas fa-file-pdf"></i></a>')
    # strip the trailing two-space break from whichever line ended up last
    out[-1] = out[-1].rstrip()
    if not url:
        out[-1] = out[-1].rstrip(" ")
    return out


def main() -> int:
    pubs = yaml.safe_load((_paths.DATA / "publications.yaml").read_text())["publications"]
    by_prefix: dict[str, list] = {}
    for p in pubs:
        by_prefix.setdefault(p["id"].split("-")[0], []).append(p)

    o = ['---', 'layout: single', 'title: "Publications"', 'permalink: /publications/',
         'author_profile: true', '---', '',
         '<!-- GENERATED by generators/generate_publications_page.py from',
         '     _dev/data/publications.yaml. Hand edits will be overwritten. -->', '',
         'Here are the publications to which I have contributed.',
         'To see them organized approximately by project, see [here](/research).', '']

    placed = 0
    for heading, anchor, prefixes in SECTIONS:
        rows: list[dict] = []
        for pre in prefixes:
            rows += by_prefix.get(pre, [])
        if not rows:
            continue
        rows.sort(key=lambda p: (-(p.get("year") or 0), p["id"]))
        head = f"## {heading}"
        if anchor:
            head = f'<h2 id="{anchor}">{heading}</h2>'
        o += ["", head, ""]
        for p in rows:
            o += entry(p)
            placed += 1

    # Students' theses live in their own record -- see data/theses.yaml for why.
    theses = yaml.safe_load((_paths.DATA / "theses.yaml").read_text())["theses"]
    if theses:
        o += ["", "## Dissertations and theses", ""]
        for t in sorted(theses, key=lambda x: (-(x.get("year") or 0), x["author"])):
            o.append(f"1. *{' '.join(t['title'].split())}*.  ")
            o.append(f" **{t['author']}**.  ")
            o.append(f" {t['degree']}, Electrical & Computer Engineering, "
                     f"Purdue University {t['year']}.  ")
            bits = []
            if t.get("pdf_url"):
                bits.append(f'<a href="{t["pdf_url"]}"><i class="fas fa-file-pdf"></i></a>')
            if t.get("slides"):
                # quote(): several decks have spaces in their names, and a raw
                # space in an href does not resolve.
                slides = urllib.parse.quote(t["slides"])
                bits.append('<a href="{{ site.url }}/{{ site.baseurl }}/{{ site.filesurl }}'
                            f'/publications/{slides}"><i class="fas fa-file-powerpoint"></i></a>')
            o[-1] = o[-1].rstrip() if not bits else o[-1]
            if bits:
                o.append(" " + " ".join(bits))

    out = _paths.SITE / "auto-publications.md"
    out.write_text("\n".join(o) + "\n")
    missing = len(pubs) - placed
    print(f"  wrote {out.name}: {placed} of {len(pubs)} records"
          + (f"  ({missing} unplaced -- unknown id prefix)" if missing else ""))
    if missing:
        seen = {p["id"].split("-")[0] for p in pubs}
        known = {x for _, _, pre in SECTIONS for x in pre}
        print(f"  unplaced prefixes: {sorted(seen - known)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
