#!/usr/bin/env python3
"""Emit the sidebar's funder list from the funding record.

The homepage used to name seven sponsors in a prose sentence. That put credit
in the one place a funder is least likely to look -- a paragraph on one page --
and it vanished the moment a visitor went anywhere else. The rail shows it on
every page instead.

DERIVED, NOT AUTHORED. Writing the names into the sidebar by hand would create
the same defect the patent records had: a second copy of a fact that drifts from
the first. It already had, quietly -- Intel's gift-in-kind sat outside the CV's
EXTERNAL GRANTS total, so neither the record nor the sentence mentioned it, and
the site credited seven sponsors when there were eight.

ORDERED BY WEIGHT, then alphabetically. NSF is ten of twenty-four awards and
belongs first; the tail is alphabetical so additions land predictably rather
than wherever the input happened to put them.

DISPLAY NAMES are derived here, not stored. A funding record should hold the
legal name -- "Qualcomm, Inc.", "OpenAI - Cybersecurity Grant Program" -- because
that is what an award is made by. A sidebar should not shout it. Deriving means
the record stays correct and the rail stays readable without a second field to
keep in sync.
"""

from __future__ import annotations

import collections
import json
import sys

import yaml

import _paths

# Legal name -> what a reader needs. Anything absent falls through unchanged, so
# a new sponsor appears correctly without touching this map.
DISPLAY = {
    "US National Science Foundation": "National Science Foundation",
    "Google, LLC": "Google",
    "Qualcomm, Inc.": "Qualcomm",
    "Socket, Inc.": "Socket",
    "OpenAI — Cybersecurity Grant Program": "OpenAI",
}


def main() -> int:
    grants = yaml.safe_load((_paths.DATA / "funding.yaml").read_text())["grants"]
    counts = collections.Counter(g["sponsor"] for g in grants)
    order = sorted(counts.items(), key=lambda kv: (-kv[1], DISPLAY.get(kv[0], kv[0])))

    out = ["# GENERATED by davis-web generators/generate_funders.py.",
           "# Source: data/funding.yaml. Do not hand-edit.",
           "heading: Research supported by",
           "sponsors:"]
    for legal, n in order:
        # json.dumps, not yaml.safe_dump: safe_dump emits a whole document,
        # trailing "..." marker and all, which is not a scalar. Its output is
        # also valid YAML double-quoted scalar syntax.
        out.append(f"  - name: {json.dumps(DISPLAY.get(legal, legal))}")
        out.append(f"    awards: {n}")

    dest = _paths.SITE / "_data/funders.yml"
    dest.write_text("\n".join(out) + "\n")
    print(f"  wrote {dest.name}: {len(order)} sponsors, {sum(counts.values())} awards")
    return 0


if __name__ == "__main__":
    sys.exit(main())
