"""The shared page shell for research-project sites.

A project page is a DEEPER PAGE of davisjam.github.io, not a microsite that
happens to share content. Everything here exists to make that true: the same
header, the same identity sidebar, the same typography, the same palette.

Every value below was MEASURED from the live site with Playwright rather than
approximated, because approximating a design you are trying to share produces a
third design. What the measurement corrected:

    body        18px / 27px, system sans, #494E52
    h1          28.13px, weight 700 -- and NOT serif. The project pages were
                using Source Serif 4, which is most of why they read as another
                website.
    h2          21.6px / 700, 1px bottom rule in #F2F3F3
    prose       max-width 864px
    nav         18px, #7A8288
    sidebar     206px, headshot + name + role + links
    logo        /images/logo-v2.png at 150x65

Palette is Purdue, and the contrast ratios decide the roles:

    Boilermaker Gold #CEB888   1.94 on white -- FAILS for text. Borders,
                               hover, rules and identity cues only.
    Aged             #8E6F3E   4.67 on white -- passes AA. This is the link
                               colour.
    Black / #494E52            21.0 / 8.42 -- text.

So gold never becomes body-text yellow, which is the failure mode a
gold-forward palette invites.

What a project may vary: its figure, title, question, local sections, content.
What it may NOT vary: masthead, font scale, page background, link colour, page
width, navigation vocabulary.
"""

from __future__ import annotations

import html

# Measured from davisjam.github.io, plus the Purdue palette. Every rule below
# refers to these; no literal colour appears twice.
TOKENS = {
    "bg": "#ffffff",
    "text": "#494E52",
    "muted": "#7A8288",
    "border": "#F2F3F3",
    "rule": "#e8e8e8",
    "accent": "#8E6F3E",        # Purdue Aged -- AA on white
    "accent_dark": "#6d552f",
    "gold": "#CEB888",          # Boilermaker Gold -- never text
    "black": "#000000",
    "steel": "#555960",
    "font": ('-apple-system, ".SFNSText-Regular", "San Francisco", Roboto, '
             '"Segoe UI", "Helvetica Neue", "Lucida Grande", Arial, sans-serif'),
}

NAV = [("Home", "https://davisjam.github.io/"),
       ("Research", "https://davisjam.github.io/research/"),
       ("Publications", "https://davisjam.github.io/publications/"),
       ("Teaching", "https://davisjam.github.io/teaching/"),
       ("Service", "https://davisjam.github.io/service/"),
       ("About", "https://davisjam.github.io/about/")]

# Icon set and destinations taken from the main site's _config.yml and
# _includes/author-profile.html -- the same icons the rest of the site uses.
# (label, href, icon-class). The label is not printed; it is the accessible
# name, because an icon-only link needs one.
PROFILE_LINKS = [
    ("Email", "mailto:davisjam@purdue.edu", "fas fa-fw fa-envelope"),
    ("Google Scholar", "https://scholar.google.com/citations?user=VSAWPQ4AAAAJ",
     "ai ai-fw ai-google-scholar"),
    ("GitHub", "https://github.com/davisjam", "fab fa-fw fa-github"),
    ("Twitter", "https://twitter.com/TheDavisJam", "fab fa-fw fa-twitter-square"),
    ("CV", "https://davisjam.github.io/files/professional/JamesDavis-CV.pdf",
     "ai ai-fw ai-cv"),
]

ICON_CSS = (
 '<link rel="stylesheet" '
 'href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.2/css/all.min.css">\n'
 '<link rel="stylesheet" '
 'href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">')

CSS = """/* GENERATED by davis-web generators/. Do not hand-edit.
   The davisjam.github.io shell, shared by every research-project page.
   Values measured from the live site; palette is Purdue. */
:root{{
  --bg:{bg}; --text:{text}; --muted:{muted}; --border:{border}; --rule:{rule};
  --accent:{accent}; --accent-dark:{accent_dark}; --gold:{gold};
  --black:{black}; --steel:{steel};
}}
*{{box-sizing:border-box}}
html{{-webkit-text-size-adjust:100%}}
body{{margin:0;background:var(--bg);color:var(--text);
  font:18px/27px {font}}}
img{{max-width:100%;height:auto}}
a{{color:var(--accent);text-decoration:none}}
a:hover{{color:var(--accent-dark);text-decoration:underline}}

/* ---- masthead: logo left, global nav right. Identical position everywhere,
   so the navigation does not jump between site and project pages. ---- */
.masthead{{border-bottom:1px solid var(--border);background:var(--bg)}}
.masthead__inner{{max-width:1600px;margin:0 auto;padding:.6rem 1.5rem;
  display:flex;align-items:center;gap:2rem;flex-wrap:wrap}}
.masthead__logo img{{width:150px;height:65px;object-fit:contain;display:block}}
.masthead nav{{margin-left:auto;display:flex;gap:1.4rem;flex-wrap:wrap;
  font-size:18px;color:var(--muted)}}
.masthead nav a{{color:var(--muted)}}
.masthead nav a:hover{{color:var(--accent);text-decoration:none}}
/* breadcrumb sits in the Research slot: Research > MAGE */
.crumb{{color:var(--muted);white-space:nowrap}}
.crumb .sep{{color:var(--gold);margin:0 .35rem}}
.crumb .here{{color:var(--text);font-weight:600}}

/* ---- shell: identity rail + content, matching the main site ---- */
.shell{{max-width:1600px;margin:0 auto;padding:2em 1.5rem 0;
  display:grid;grid-template-columns:206px minmax(0,1fr);gap:3rem}}
.rail{{font-size:16px;line-height:1.5}}
.rail img.avatar{{width:150px;border-radius:50%;display:block;margin-bottom:.8rem}}
.rail .name{{font-weight:700;color:var(--text);margin:0 0 .15rem}}
.rail .role{{color:var(--muted);font-size:15px;margin:0 0 .8rem}}
/* Icon row, as on the rest of the site. Purdue gold -- but AGED (#8E6F3E),
   not Boilermaker (#CEB888): these are meaningful non-text content, so WCAG
   wants 3:1, and Boilermaker sits at 1.94 on white. Aged is 4.67 and is still
   a Purdue gold. Boilermaker carries the hover underline instead, where a
   low-contrast accent is decorative rather than load-bearing. */
.rail .icons{{list-style:none;margin:0;padding:0;display:flex;gap:.85rem;flex-wrap:wrap}}
.rail .icons a{{color:var(--accent);font-size:22px;line-height:1;display:inline-block;
  padding:.15rem;border-bottom:2px solid transparent}}
.rail .icons a:hover{{color:var(--accent-dark);border-bottom-color:var(--gold);
  text-decoration:none}}
.rail .icons a:focus-visible{{outline:2px solid var(--accent);outline-offset:2px}}
.main{{min-width:0}}
/* A long title, URL or identifier must shrink with its column rather than
   forcing the page wider. */
.main,.rail,.bib,.split>*{{min-width:0}}
h1,h2,h3,p,.bib .ti,.bib .vn,.support dd{{overflow-wrap:anywhere}}

h1,h2,h3{{color:var(--text);font-family:{font};line-height:1.2}}
h1{{font-size:28.13px;font-weight:700;margin:0 0 .3rem}}
h2{{font-size:21.6px;font-weight:700;margin:2.2rem 0 .8rem;
  padding-bottom:.4rem;border-bottom:1px solid var(--border)}}
h3{{font-size:18px;font-weight:700;margin:1.4rem 0 .3rem}}
p{{max-width:864px}}
.lede{{font-size:19px;color:var(--steel);max-width:864px;margin:0 0 1.1rem}}

/* project-local navigation: inside the content column, BELOW the intro.
   It never replaces the global nav. */
/* Flex with wrap, not inline anchors. The generator emits no whitespace
   BETWEEN anchors, so as inline content the row had no break opportunity and
   overflowed to 370px inside a 320px viewport. */
.jump{{margin:1.2rem 0 0;padding:.55rem 0;border-top:1px solid var(--rule);
  border-bottom:1px solid var(--rule);font-size:16px;
  display:flex;flex-wrap:wrap;gap:.3rem 1.3rem}}
.jump a{{color:var(--muted);white-space:nowrap}}
.jump a:hover{{color:var(--accent)}}

.split{{display:grid;gap:2rem;grid-template-columns:minmax(0,1fr) minmax(0,1.05fr);
  align-items:start}}
.split p{{max-width:none}}
figure{{margin:0}}
figure img{{width:100%;height:auto;display:block}}
figcaption{{font-size:15px;color:var(--muted);margin-top:.6rem;padding-top:.6rem;
  border-top:1px solid var(--rule);max-width:864px}}

.bib{{margin:0;max-width:864px}}
.bib .yr{{font-size:14px;letter-spacing:.06em;color:var(--muted);
  margin:1.4rem 0 .3rem;font-weight:700}}
.bib .e{{padding:.5rem 0;border-bottom:1px solid var(--border)}}
.bib .e:last-child{{border-bottom:0}}
.bib .ti{{font-weight:600;color:var(--text)}}
.bib .vn{{color:var(--muted);font-size:16px}}
.bib .note{{margin-top:.2rem;font-size:17px}}
.bib .ln{{font-size:16px;margin-top:.2rem}}
.bib .ln a{{margin-right:.9rem}}
.award{{font-size:13px;color:var(--accent-dark);background:#faf6ee;
  border:1px solid var(--gold);border-radius:2px;padding:0 .3rem;margin-left:.35rem}}

.support{{max-width:864px}}
.support dt{{font-weight:700;margin-top:.9rem}}
.support dd{{margin:.1rem 0 0;color:var(--muted)}}

footer.site{{max-width:1600px;margin:3rem auto 0;padding:1.3rem 1.5rem 3rem;
  border-top:1px solid var(--border);color:var(--muted);font-size:16px}}
footer.site a{{color:var(--muted)}}
footer.site a:hover{{color:var(--accent)}}

/* Same reflow as the rest of the site: the rail stacks above the content
   rather than becoming a project-specific mobile layout. */
@media (max-width:900px){{
  .shell{{grid-template-columns:1fr;gap:1.5rem;padding-top:1.2rem}}
  .rail{{display:flex;align-items:center;gap:1rem;flex-wrap:wrap}}
  .rail img.avatar{{width:70px;margin:0}}
  .rail ul{{display:flex;gap:1rem;flex-wrap:wrap}}
  .split{{grid-template-columns:1fr}}
}}
@media print{{.masthead nav,.jump{{display:none}} a{{color:inherit}}}}
"""


def esc(s) -> str:
    return html.escape(str(s), quote=True)


def masthead(short_name: str) -> str:
    """Global nav, with the Research item replaced by `Research > <slug>`.

    The breadcrumb occupies the Research slot rather than being added beside it,
    so the navigation keeps the same shape on every page.
    """
    items = []
    for label, url in NAV:
        if label == "Research":
            items.append(
                f'<span class="crumb"><a href="{url}">Research</a>'
                f'<span class="sep">&rsaquo;</span>'
                f'<span class="here">{esc(short_name)}</span></span>')
        else:
            items.append(f'<a href="{url}">{label}</a>')
    return f"""<header class="masthead">
  <div class="masthead__inner">
    <a class="masthead__logo" href="https://davisjam.github.io/">
      <img src="assets/logo-v2.png" alt="Duality Lab"></a>
    <nav>{''.join(items)}</nav>
  </div>
</header>"""


def rail() -> str:
    links = "".join(
        f'<li><a href="{u}" aria-label="{esc(l)}" title="{esc(l)}">'
        f'<i class="{ic}" aria-hidden="true"></i></a></li>'
        for l, u, ic in PROFILE_LINKS)
    return f"""<aside class="rail">
  <img class="avatar" src="assets/JamesDavis.jpg" alt="James Davis">
  <p class="name">James Davis, PhD</p>
  <p class="role">Assistant Professor,<br>ECE&#64;Purdue</p>
  <ul class="icons">{links}</ul>
</aside>"""


def jump(sections: list[tuple[str, str]]) -> str:
    if not sections:
        return ""
    return ('<nav class="jump">'
            + "".join(f'<a href="#{sid}">{esc(label)}</a>' for sid, label in sections)
            + "</nav>")


def bibliography(entries: list[dict], project: str) -> str:
    by_year: dict[int, list] = {}
    for p in entries:
        by_year.setdefault(p.get("year") or 0, []).append(p)
    out = ['<div class="bib">']
    for yr in sorted(by_year, reverse=True):
        out.append(f'<div class="yr">{yr if yr else "In preparation"}</div>')
        for p in by_year[yr]:
            out.append('<div class="e">')
            awards = "".join(f'<span class="award">{esc(a.replace("-", " "))}</span>'
                             for a in (p.get("awards") or []))
            # The TITLE is the link. A separate [Paper] chip beside a linked
            # title is redundant, and it is what let unlinked titles hide.
            url = p.get("paper_url")
            t = f'<a href="{esc(url)}">{esc(p["title"])}</a>' if url else esc(p["title"])
            out.append(f'<div class="ti">{t}{awards}</div>')
            if p.get("venue"):
                out.append(f'<div class="vn">{esc(p["venue"])}</div>')
            note = (p.get("program_notes") or {}).get(project)
            if note:
                out.append(f'<div class="note">{esc(note)}</div>')
            # Only DISTINCT artifacts, never a second route to the paper itself.
            resolved = p.get("paper_url")
            links = [(n, u) for n, u in (p.get("links") or {}).items()
                     if u and u != resolved and n not in ("paper", "record")
                     and not str(u).startswith("/files/")]
            if links:
                out.append('<div class="ln">' + "".join(
                    f'<a href="{esc(u)}">{esc(n.capitalize())}</a>' for n, u in links) + "</div>")
            out.append("</div>")
    out.append("</div>")
    return "\n".join(out)


def funding(grants: list[dict]) -> str:
    out = ['<dl class="support">']
    for g in grants:
        num = f" (#{g['number']})" if g.get("number") else ""
        t = f'<a href="{esc(g["url"])}">{esc(g["title"])}</a>' if g.get("url") else esc(g["title"])
        out.append(f"<dt>{esc(g['sponsor'])}</dt><dd>{t}{num}</dd>")
    out.append("</dl>")
    return "\n".join(out)


def footer() -> str:
    return """<footer class="site">
  <p><a href="https://davisjam.github.io/research/">&larr; All research</a></p>
  <p>Duality Lab &middot; Elmore Family School of Electrical and Computer
     Engineering &middot; Purdue University</p>
</footer>"""


def page(title: str, question: str, intro_html: str, url: str, body: str,
         sections: list[tuple[str, str]], short_name: str) -> str:
    desc = " ".join(question.split())[:180]
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} &middot; Duality Lab</title>
<meta name="description" content="{esc(desc)}">
<meta name="author" content="James C. Davis">
<link rel="canonical" href="{esc(url)}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{esc(url)}">
<meta property="og:type" content="website">
{ICON_CSS}
<link rel="stylesheet" href="assets/site.css">
</head>
<body>
{masthead(short_name)}
<div class="shell">
{rail()}
<main class="main">
<h1>{esc(title)}</h1>
<p class="lede">{esc(question)}</p>
{intro_html}
{jump(sections)}
{body}
</main>
</div>
{footer()}
</body>
</html>
"""
